app = "sohbet-backend"
primary_region = "ams"

[build]
dockerfile = "Dockerfile.backend"  # This tells Fly to use Dockerfile.backend

[env]
  SOHBET_JWT_SECRET = "your-secret-here"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  
  [[services.ports]]
    port = 8081
    handlers = ["tcp"]

[checks]
  [checks.http_check]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/api/health"
    protocol = "http"
    timeout = "5s"
