name: Brilliant_Curve
description: 'The Brilliant_Curve agent autonomously manages security, feature completion,
  and future roadmap execution for the Sohbet academic social media platform. It coordinates
  between the React/TypeScript frontend (Vercel) and the C++17/SQLite backend (Fly.io),
  updating its own progress tracker using GNOME symbolic icons defined in icons.md.

  '
permissions:
- read
- write
- workflows
visible_to:
- all
stateful_sections:
- Progress Tracker
on_command_update: commit
commit_message_template: '[agent] {command_name}: updated progress tracker status'
progress_tracker:
- task: Implement Email Verification
  status: Completed
  icon: document-save-symbolic
- task: Add Rate Limiting
  status: Completed
  icon: document-save-symbolic
- task: Secure JWT Authentication
  status: Completed
  icon: document-save-symbolic
- task: Finalize Voice Channel
  status: Completed
  icon: document-save-symbolic
- task: Implement File Sharing
  status: Completed
  icon: document-save-symbolic
- task: Configure Deployment Communication
  status: Completed
  icon: document-save-symbolic
- task: Implement Advanced Search
  status: Completed
  icon: document-save-symbolic
- task: Extend WebRTC Video Sharing
  status: Completed
  icon: document-save-symbolic
- task: Build Analytics Dashboard
  status: Completed
  icon: document-save-symbolic
- task: Add Structured Q&A System
  status: Completed
  icon: document-save-symbolic
- task: Enforce Code Standards
  status: Completed
  icon: document-save-symbolic
- task: Optimize SQLite Performance
  status: Completed
  icon: document-save-symbolic
- task: Update API Documentation
  status: Completed
  icon: document-save-symbolic
- task: Apply API Versioning
  status: Completed
  icon: document-save-symbolic
- task: Synchronize Deployments
  status: Completed
  icon: document-save-symbolic
- task: Validate Cross-Platform Auth
  status: Completed
  icon: document-save-symbolic
command_library:
  Security & Authentication:
  - implement-email-verification
  - add-rate-limiting
  - secure-jwt-authentication
  Feature Completion:
  - finalize-voice-channel
  - implement-file-sharing
  - configure-deployment-communication
  Future Roadmap:
  - implement-advanced-search
  - extend-webrtc-video-sharing
  - build-analytics-dashboard
  - add-structured-qa-system
  Development Standards:
  - enforce-code-standards
  - optimize-sqlite-performance
  - update-api-documentation
  - apply-api-versioning
  System Integration:
  - synchronize-deployments
  - validate-cross-platform-auth
